### ISSUE TITLE
centos8 is dead...

### ISSUE THREAD

**Issue by FrancoisXavierNoe** [robertdebock/rpmbuild-action#2]
Hello !

When running the github action
```
CentOS Linux 8 - AppStream                       92  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

Is it possible to add rockylinux distribution ?

The input.distribution seems not working
```
      - name: Build RPM
        uses: robertdebock/rpmbuild-action@1.0.0
        with:
          distribution: rockylinux-8
```
Result is
`Warning: Unexpected input(s) 'distribution', valid inputs are ['entryPoint', 'args']`

Workaround, bypass the github action...
```
      - name: Build RPM
        uses: docker://robertdebock/github-action-rpmbuild:rockylinux-8
```
